FROM mcr.microsoft.com/dotnet/sdk:9.0

WORKDIR /app

RUN mkdir -p /root/.aspnet/DataProtection-Keys

ENV NUGET_PACKAGES=/root/.nuget/packages
RUN mkdir -p /root/.nuget/packages

COPY ["Project-Echo.csproj", "./"]
RUN dotnet nuget locals all --clear && \
    dotnet restore --packages /root/.nuget/packages

COPY . .

EXPOSE 8080
EXPOSE 443

ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://+:8080
RUN apt-get update \
    && apt-get install -y --no-install-recommends ffmpeg curl ca-certificates python3 \
    && curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp \
    && chmod a+rx /usr/local/bin/yt-dlp \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["dotnet", "watch", "run"] 