name: Deploy to Render

on:
  push:
    branches:
      - main  # ou a branch que você usa

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
